$axure.loadCurrentPage({
  "url":"02新增古玩城.html",
  "generationDate":new Date(1482310120544.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"118fc9668e514bc99aa3ab3d1a164aec",
    "type":"Axure:Page",
    "name":"02新增古玩城",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"274d205a6baf430a99fa2a277d60b3b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1920,
              "height":1139}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f85774909d554cdaa924d26b171dccab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1920,
                  "height":1139}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02新增古玩城/u0.png"}},
{
          "id":"2e17cf019b014266b1ddf11bbe3a374e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":90,
              "y":120},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1f000b314b74380a76e1a92f5cff088",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":90,
                  "y":120},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 00登陆",
                      "target":{
                        "targetType":"page",
                        "url":"00登陆.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e5447a46d2d46be9f2c9d326b73ed9a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":757},
            "size":{
              "width":230,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36d4f04a3b2e4768b2068d07277594d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":757},
                "size":{
                  "width":230,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 01列表页",
                      "target":{
                        "targetType":"page",
                        "url":"01列表页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d42ae32f3c7e496fa3773579dd31fed0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":556},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a21d45c9ca784a3c96ea17b12856b12c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":556},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 01用户列表",
                      "target":{
                        "targetType":"page",
                        "url":"01用户列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1db938815e8f48bbb6da2ca5e00183c0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":405},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3350a1b501cc441189cc6cea08a03217",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":405},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 01分类管理",
                      "target":{
                        "targetType":"page",
                        "url":"01分类管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13b0789afca04f7ba21eef19e34e9fea",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":205},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8d1d4c1db3148c69eece2169c4ccdb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":205},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 01标签管理",
                      "target":{
                        "targetType":"page",
                        "url":"01标签管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68658cecd234491a954d6179a60920cc",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":255},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d06719192864b6680f97c689e9a6986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":255},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 01标签管理",
                      "target":{
                        "targetType":"page",
                        "url":"01标签管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d77a634b5c1d48e7950a457dc4eab5f4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":305},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48aae363399449a6a05178a6b9b06dc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":305},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 01古玩城管理",
                      "target":{
                        "targetType":"page",
                        "url":"01古玩城管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"186db08d6e6c45d380e6f617cb89e528",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":355},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3de1229f31a9418faf3f2d72a6d0aa51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":355},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 01店铺管理",
                      "target":{
                        "targetType":"page",
                        "url":"01店铺管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"329cf3ada8da46f49dc354962d1cf468",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1800,
              "y":85},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e80957a42f146c8847c1dc48e446fa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1800,
                  "y":85},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"019dff994684484e8fef012957cb9d2b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":240,
              "y":1065},
            "size":{
              "width":1660,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2460025798647b3adfbae70996ae4e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":240,
                  "y":1065},
                "size":{
                  "width":1660,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a0faacb5b7d47bba677243f5884ba69",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":155},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"878d7ef47b594872a4ec42c9950fff91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":155},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 01首页",
                      "target":{
                        "targetType":"page",
                        "url":"01首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "274d205a6baf430a99fa2a277d60b3b6":{
      "scriptId":"u0"},
    "f85774909d554cdaa924d26b171dccab":{
      "scriptId":"u1"},
    "2e17cf019b014266b1ddf11bbe3a374e":{
      "scriptId":"u2"},
    "d1f000b314b74380a76e1a92f5cff088":{
      "scriptId":"u3"},
    "5e5447a46d2d46be9f2c9d326b73ed9a":{
      "scriptId":"u4"},
    "36d4f04a3b2e4768b2068d07277594d4":{
      "scriptId":"u5"},
    "d42ae32f3c7e496fa3773579dd31fed0":{
      "scriptId":"u6"},
    "a21d45c9ca784a3c96ea17b12856b12c":{
      "scriptId":"u7"},
    "1db938815e8f48bbb6da2ca5e00183c0":{
      "scriptId":"u8"},
    "3350a1b501cc441189cc6cea08a03217":{
      "scriptId":"u9"},
    "13b0789afca04f7ba21eef19e34e9fea":{
      "scriptId":"u10"},
    "e8d1d4c1db3148c69eece2169c4ccdb2":{
      "scriptId":"u11"},
    "68658cecd234491a954d6179a60920cc":{
      "scriptId":"u12"},
    "3d06719192864b6680f97c689e9a6986":{
      "scriptId":"u13"},
    "d77a634b5c1d48e7950a457dc4eab5f4":{
      "scriptId":"u14"},
    "48aae363399449a6a05178a6b9b06dc3":{
      "scriptId":"u15"},
    "186db08d6e6c45d380e6f617cb89e528":{
      "scriptId":"u16"},
    "3de1229f31a9418faf3f2d72a6d0aa51":{
      "scriptId":"u17"},
    "329cf3ada8da46f49dc354962d1cf468":{
      "scriptId":"u18"},
    "0e80957a42f146c8847c1dc48e446fa4":{
      "scriptId":"u19"},
    "019dff994684484e8fef012957cb9d2b":{
      "scriptId":"u20"},
    "d2460025798647b3adfbae70996ae4e3":{
      "scriptId":"u21"},
    "6a0faacb5b7d47bba677243f5884ba69":{
      "scriptId":"u22"},
    "878d7ef47b594872a4ec42c9950fff91":{
      "scriptId":"u23"}}});